dist: xenial
sudo: false
language: python
env:
  - DJANGO_VERSION="Django>=2.0,<2.1"
  - DJANGO_VERSION="django>=2.1.9"
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - '3.7-dev'
  - '3.7'
before_script:
  - pip install coverage coveralls
  - pip install -q $DJANGO_VERSION
  - python setup.py install
script:
  - django-admin --version
  - coverage run manage.py test --settings=test_settings
after_script:
  - coveralls
matrix:
   exclude:
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
        python: "3.4"
      - env: DJANGO_VERSION="django>=2.1.9"
        python: "3.4"
   allow_failures:
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
